packages:
  - theme
  - docs
  - demo
  - scripts
catalog:
  typescript: ^5.7.3
  # https://github.com/vuejs/language-tools/issues/5018
  vue-tsc: 2.0.26
  valaxy: ^0.22.13
  valaxy-addon-algolia: ^0.1.0
  valaxy-addon-bangumi: ^0.2.2
  valaxy-addon-live2d: ^0.3.0
  valaxy-addon-meting: ^0.1.4
  valaxy-addon-twikoo: ^0.0.3
  valaxy-addon-waline: ^0.2.0
