packages:
  - theme
  - docs
  - demos/*
  - packages/*
  - scripts
catalog:
  typescript: ^5.3.3
  valaxy: ^0.20.7
  valaxy-addon-algolia: ^0.1.0
  valaxy-addon-bangumi: ^0.2.2
  valaxy-addon-git-log: ^0.1.1
  valaxy-addon-live2d: ^0.3.0
  valaxy-addon-meting: ^0.1.4
  valaxy-addon-twikoo: ^0.0.3
  valaxy-addon-waline: ^0.2.0
