catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - theme
  - docs
  - demo
  - scripts
catalog:
  '@antfu/eslint-config': ^6.5.1
  '@ctrl/tinycolor': ^4.2.0
  '@iconify-json/fa': ^1.2.2
  '@iconify-json/fa6-solid': ^1.2.4
  '@iconify-json/line-md': ^1.2.11
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/qlementine-icons': ^1.2.13
  '@iconify-json/simple-icons': ^1.2.62
  '@interactjs/types': ^1.10.27
  '@unocss/eslint-plugin': ^66.5.10
  bumpp: ^10.3.2
  cross-env: ^10.1.0
  eslint: ^9.39.1
  eslint-plugin-format: ^1.1.0
  interactjs: ^1.10.27
  lenis: ^1.3.15
  monaco-editor: ^0.52.2
  rimraf: ^6.1.2
  simple-git-hooks: ^2.13.1
  stylelint: ^16.26.1
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard-scss: ^14.0.0
  stylelint-gamut: ^1.3.4
  taze: ^19.9.2
  tsx: ^4.21.0
  typeit: ^8.8.7
  typescript: ^5.9.3
  valaxy: ^0.26.10
  valaxy-addon-algolia: ^0.2.0
  valaxy-addon-bangumi: ^0.2.2
  valaxy-addon-components: ^0.1.0
  valaxy-addon-git-log: ^0.3.2
  valaxy-addon-meting: ^0.1.4
  valaxy-addon-twikoo: ^0.0.3
  valaxy-addon-waline: ^0.2.1
  valaxy-theme-oceanus: ^0.1.0
  vue-progressive-image: ^5.0.6
  vue-toastification: 2.0.0-rc.5
  vue-tsc: ^3.1.7
  zx: ^8.8.5
