/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/graph': RouteRecordInfo<'/graph', '/graph', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/2024_01_11': RouteRecordInfo<'/posts/2024_01_11', '/posts/2024_01_11', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy': RouteRecordInfo<'/posts/hello-valaxy copy', '/posts/hello-valaxy copy', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 10': RouteRecordInfo<'/posts/hello-valaxy copy 10', '/posts/hello-valaxy copy 10', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 11': RouteRecordInfo<'/posts/hello-valaxy copy 11', '/posts/hello-valaxy copy 11', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 12': RouteRecordInfo<'/posts/hello-valaxy copy 12', '/posts/hello-valaxy copy 12', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 13': RouteRecordInfo<'/posts/hello-valaxy copy 13', '/posts/hello-valaxy copy 13', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 14': RouteRecordInfo<'/posts/hello-valaxy copy 14', '/posts/hello-valaxy copy 14', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 15': RouteRecordInfo<'/posts/hello-valaxy copy 15', '/posts/hello-valaxy copy 15', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 16': RouteRecordInfo<'/posts/hello-valaxy copy 16', '/posts/hello-valaxy copy 16', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 17': RouteRecordInfo<'/posts/hello-valaxy copy 17', '/posts/hello-valaxy copy 17', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 18': RouteRecordInfo<'/posts/hello-valaxy copy 18', '/posts/hello-valaxy copy 18', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 19': RouteRecordInfo<'/posts/hello-valaxy copy 19', '/posts/hello-valaxy copy 19', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 2': RouteRecordInfo<'/posts/hello-valaxy copy 2', '/posts/hello-valaxy copy 2', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 20': RouteRecordInfo<'/posts/hello-valaxy copy 20', '/posts/hello-valaxy copy 20', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 21': RouteRecordInfo<'/posts/hello-valaxy copy 21', '/posts/hello-valaxy copy 21', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 22': RouteRecordInfo<'/posts/hello-valaxy copy 22', '/posts/hello-valaxy copy 22', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 23': RouteRecordInfo<'/posts/hello-valaxy copy 23', '/posts/hello-valaxy copy 23', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 3': RouteRecordInfo<'/posts/hello-valaxy copy 3', '/posts/hello-valaxy copy 3', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 4': RouteRecordInfo<'/posts/hello-valaxy copy 4', '/posts/hello-valaxy copy 4', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 5': RouteRecordInfo<'/posts/hello-valaxy copy 5', '/posts/hello-valaxy copy 5', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 6': RouteRecordInfo<'/posts/hello-valaxy copy 6', '/posts/hello-valaxy copy 6', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 7': RouteRecordInfo<'/posts/hello-valaxy copy 7', '/posts/hello-valaxy copy 7', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 8': RouteRecordInfo<'/posts/hello-valaxy copy 8', '/posts/hello-valaxy copy 8', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy copy 9': RouteRecordInfo<'/posts/hello-valaxy copy 9', '/posts/hello-valaxy copy 9', Record<never, never>, Record<never, never>>,
    '/posts/Japan': RouteRecordInfo<'/posts/Japan', '/posts/Japan', Record<never, never>, Record<never, never>>,
    '/posts/测试': RouteRecordInfo<'/posts/测试', '/posts/测试', Record<never, never>, Record<never, never>>,
    '/posts/测试 copy': RouteRecordInfo<'/posts/测试 copy', '/posts/测试 copy', Record<never, never>, Record<never, never>>,
    '/posts/测试 copy 10': RouteRecordInfo<'/posts/测试 copy 10', '/posts/测试 copy 10', Record<never, never>, Record<never, never>>,
    '/posts/测试 copy 2': RouteRecordInfo<'/posts/测试 copy 2', '/posts/测试 copy 2', Record<never, never>, Record<never, never>>,
    '/posts/测试 copy 3': RouteRecordInfo<'/posts/测试 copy 3', '/posts/测试 copy 3', Record<never, never>, Record<never, never>>,
    '/posts/测试 copy 4': RouteRecordInfo<'/posts/测试 copy 4', '/posts/测试 copy 4', Record<never, never>, Record<never, never>>,
    '/posts/测试 copy 5': RouteRecordInfo<'/posts/测试 copy 5', '/posts/测试 copy 5', Record<never, never>, Record<never, never>>,
    '/posts/测试 copy 6': RouteRecordInfo<'/posts/测试 copy 6', '/posts/测试 copy 6', Record<never, never>, Record<never, never>>,
    '/posts/测试 copy 7': RouteRecordInfo<'/posts/测试 copy 7', '/posts/测试 copy 7', Record<never, never>, Record<never, never>>,
    '/posts/测试 copy 8': RouteRecordInfo<'/posts/测试 copy 8', '/posts/测试 copy 8', Record<never, never>, Record<never, never>>,
    '/posts/测试 copy 9': RouteRecordInfo<'/posts/测试 copy 9', '/posts/测试 copy 9', Record<never, never>, Record<never, never>>,
  }
}
