/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/anime/': RouteRecordInfo<
      '/anime/',
      '/anime',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comment/': RouteRecordInfo<
      '/comment/',
      '/comment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes/': RouteRecordInfo<
      '/notes/',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/categories-a-b': RouteRecordInfo<
      '/posts/categories-a-b',
      '/posts/categories-a-b',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/categories-a-b-c': RouteRecordInfo<
      '/posts/categories-a-b-c',
      '/posts/categories-a-b-c',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/draft': RouteRecordInfo<
      '/posts/draft',
      '/posts/draft',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/encrypted-part-post': RouteRecordInfo<
      '/posts/encrypted-part-post',
      '/posts/encrypted-part-post',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/encrypted-post': RouteRecordInfo<
      '/posts/encrypted-post',
      '/posts/encrypted-post',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/katex': RouteRecordInfo<
      '/posts/katex',
      '/posts/katex',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/long-toc': RouteRecordInfo<
      '/posts/long-toc',
      '/posts/long-toc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/lots-of-images': RouteRecordInfo<
      '/posts/lots-of-images',
      '/posts/lots-of-images',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mermaid': RouteRecordInfo<
      '/posts/mermaid',
      '/posts/mermaid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/nested/a/b/c': RouteRecordInfo<
      '/posts/nested/a/b/c',
      '/posts/nested/a/b/c',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/test': RouteRecordInfo<
      '/posts/test',
      '/posts/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/test-tags': RouteRecordInfo<
      '/posts/test-tags',
      '/posts/test-tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/theme-sakura': RouteRecordInfo<
      '/posts/theme-sakura',
      '/posts/theme-sakura',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search/': RouteRecordInfo<
      '/search/',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    '../theme/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    '../node_modules/.pnpm/valaxy@0.26.10_@babel+parser@7.28.5_@types+markdown-it@14.1.2_@types+node@22.9.0_@vue+c_8678bbc3b0fc3e5d930fbd2f480d6f4b/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/anime/index.md': {
      routes:
        | '/anime/'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/comment/index.md': {
      routes:
        | '/comment/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'pages/notes/index.md': {
      routes:
        | '/notes/'
      views:
        | never
    }
    '../theme/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'pages/posts/categories-a-b.md': {
      routes:
        | '/posts/categories-a-b'
      views:
        | never
    }
    'pages/posts/categories-a-b-c.md': {
      routes:
        | '/posts/categories-a-b-c'
      views:
        | never
    }
    'pages/posts/draft.md': {
      routes:
        | '/posts/draft'
      views:
        | never
    }
    'pages/posts/encrypted-part-post.md': {
      routes:
        | '/posts/encrypted-part-post'
      views:
        | never
    }
    'pages/posts/encrypted-post.md': {
      routes:
        | '/posts/encrypted-post'
      views:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
    }
    'pages/posts/katex.md': {
      routes:
        | '/posts/katex'
      views:
        | never
    }
    'pages/posts/long-toc.md': {
      routes:
        | '/posts/long-toc'
      views:
        | never
    }
    'pages/posts/lots-of-images.md': {
      routes:
        | '/posts/lots-of-images'
      views:
        | never
    }
    'pages/posts/mermaid.md': {
      routes:
        | '/posts/mermaid'
      views:
        | never
    }
    'pages/posts/nested/a/b/c.md': {
      routes:
        | '/posts/nested/a/b/c'
      views:
        | never
    }
    'pages/posts/test.md': {
      routes:
        | '/posts/test'
      views:
        | never
    }
    'pages/posts/test-tags.md': {
      routes:
        | '/posts/test-tags'
      views:
        | never
    }
    'pages/posts/theme-sakura.md': {
      routes:
        | '/posts/theme-sakura'
      views:
        | never
    }
    'pages/search/index.md': {
      routes:
        | '/search/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
