/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/doc': RouteRecordInfo<'/posts/doc', '/posts/doc', Record<never, never>, Record<never, never>>,
    '/posts/doc10': RouteRecordInfo<'/posts/doc10', '/posts/doc10', Record<never, never>, Record<never, never>>,
    '/posts/doc11': RouteRecordInfo<'/posts/doc11', '/posts/doc11', Record<never, never>, Record<never, never>>,
    '/posts/doc12': RouteRecordInfo<'/posts/doc12', '/posts/doc12', Record<never, never>, Record<never, never>>,
    '/posts/doc13': RouteRecordInfo<'/posts/doc13', '/posts/doc13', Record<never, never>, Record<never, never>>,
    '/posts/doc14': RouteRecordInfo<'/posts/doc14', '/posts/doc14', Record<never, never>, Record<never, never>>,
    '/posts/doc15': RouteRecordInfo<'/posts/doc15', '/posts/doc15', Record<never, never>, Record<never, never>>,
    '/posts/doc2': RouteRecordInfo<'/posts/doc2', '/posts/doc2', Record<never, never>, Record<never, never>>,
    '/posts/doc3': RouteRecordInfo<'/posts/doc3', '/posts/doc3', Record<never, never>, Record<never, never>>,
    '/posts/doc4': RouteRecordInfo<'/posts/doc4', '/posts/doc4', Record<never, never>, Record<never, never>>,
    '/posts/doc5': RouteRecordInfo<'/posts/doc5', '/posts/doc5', Record<never, never>, Record<never, never>>,
    '/posts/doc6': RouteRecordInfo<'/posts/doc6', '/posts/doc6', Record<never, never>, Record<never, never>>,
    '/posts/doc7': RouteRecordInfo<'/posts/doc7', '/posts/doc7', Record<never, never>, Record<never, never>>,
    '/posts/doc8': RouteRecordInfo<'/posts/doc8', '/posts/doc8', Record<never, never>, Record<never, never>>,
    '/posts/doc9': RouteRecordInfo<'/posts/doc9', '/posts/doc9', Record<never, never>, Record<never, never>>,
    '/posts/theme-sakura': RouteRecordInfo<'/posts/theme-sakura', '/posts/theme-sakura', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
