/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/components/': RouteRecordInfo<'/components/', '/components', Record<never, never>, Record<never, never>>,
    '/components/SakuraGlitchText': RouteRecordInfo<'/components/SakuraGlitchText', '/components/SakuraGlitchText', Record<never, never>, Record<never, never>>,
    '/components/SakuraTypewriter': RouteRecordInfo<'/components/SakuraTypewriter', '/components/SakuraTypewriter', Record<never, never>, Record<never, never>>,
    '/examples/': RouteRecordInfo<'/examples/', '/examples', Record<never, never>, Record<never, never>>,
    '/examples/animation': RouteRecordInfo<'/examples/animation', '/examples/animation', Record<never, never>, Record<never, never>>,
    '/examples/config': RouteRecordInfo<'/examples/config', '/examples/config', Record<never, never>, Record<never, never>>,
    '/guide/': RouteRecordInfo<'/guide/', '/guide', Record<never, never>, Record<never, never>>,
    '/guide/getting-started/frontmatter-config': RouteRecordInfo<'/guide/getting-started/frontmatter-config', '/guide/getting-started/frontmatter-config', Record<never, never>, Record<never, never>>,
    '/guide/getting-started/installation': RouteRecordInfo<'/guide/getting-started/installation', '/guide/getting-started/installation', Record<never, never>, Record<never, never>>,
    '/guide/getting-started/site-config': RouteRecordInfo<'/guide/getting-started/site-config', '/guide/getting-started/site-config', Record<never, never>, Record<never, never>>,
    '/guide/getting-started/theme-config': RouteRecordInfo<'/guide/getting-started/theme-config', '/guide/getting-started/theme-config', Record<never, never>, Record<never, never>>,
    '/guide/getting-started/update': RouteRecordInfo<'/guide/getting-started/update', '/guide/getting-started/update', Record<never, never>, Record<never, never>>,
    '/guide/theme-config/404-page': RouteRecordInfo<'/guide/theme-config/404-page', '/guide/theme-config/404-page', Record<never, never>, Record<never, never>>,
    '/guide/theme-config/footer': RouteRecordInfo<'/guide/theme-config/footer', '/guide/theme-config/footer', Record<never, never>, Record<never, never>>,
    '/guide/theme-config/home-page': RouteRecordInfo<'/guide/theme-config/home-page', '/guide/theme-config/home-page', Record<never, never>, Record<never, never>>,
    '/guide/theme-config/links-page': RouteRecordInfo<'/guide/theme-config/links-page', '/guide/theme-config/links-page', Record<never, never>, Record<never, never>>,
    '/guide/theme-config/nav': RouteRecordInfo<'/guide/theme-config/nav', '/guide/theme-config/nav', Record<never, never>, Record<never, never>>,
    '/guide/theme-config/post-list': RouteRecordInfo<'/guide/theme-config/post-list', '/guide/theme-config/post-list', Record<never, never>, Record<never, never>>,
    '/guide/theme-config/post-page': RouteRecordInfo<'/guide/theme-config/post-page', '/guide/theme-config/post-page', Record<never, never>, Record<never, never>>,
    '/guide/theme-config/sidebar': RouteRecordInfo<'/guide/theme-config/sidebar', '/guide/theme-config/sidebar', Record<never, never>, Record<never, never>>,
    '/releases': RouteRecordInfo<'/releases', '/releases', Record<never, never>, Record<never, never>>,
  }
}
