/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/api/': RouteRecordInfo<'/api/', '/api', Record<never, never>, Record<never, never>>,
    '/api/addon': RouteRecordInfo<'/api/addon', '/api/addon', Record<never, never>, Record<never, never>>,
    '/components/banner': RouteRecordInfo<'/components/banner', '/components/banner', Record<never, never>, Record<never, never>>,
    '/components/footer': RouteRecordInfo<'/components/footer', '/components/footer', Record<never, never>, Record<never, never>>,
    '/components/navbar': RouteRecordInfo<'/components/navbar', '/components/navbar', Record<never, never>, Record<never, never>>,
    '/components/sidebar': RouteRecordInfo<'/components/sidebar', '/components/sidebar', Record<never, never>, Record<never, never>>,
    '/config/config': RouteRecordInfo<'/config/config', '/config/config', Record<never, never>, Record<never, never>>,
    '/config/container': RouteRecordInfo<'/config/container', '/config/container', Record<never, never>, Record<never, never>>,
    '/config/home': RouteRecordInfo<'/config/home', '/config/home', Record<never, never>, Record<never, never>>,
    '/config/overview': RouteRecordInfo<'/config/overview', '/config/overview', Record<never, never>, Record<never, never>>,
    '/config/pagination': RouteRecordInfo<'/config/pagination', '/config/pagination', Record<never, never>, Record<never, never>>,
    '/config/site': RouteRecordInfo<'/config/site', '/config/site', Record<never, never>, Record<never, never>>,
    '/examples/code-height-limit': RouteRecordInfo<'/examples/code-height-limit', '/examples/code-height-limit', Record<never, never>, Record<never, never>>,
    '/examples/docs': RouteRecordInfo<'/examples/docs', '/examples/docs', Record<never, never>, Record<never, never>>,
    '/guide/getting-started': RouteRecordInfo<'/guide/getting-started', '/guide/getting-started', Record<never, never>, Record<never, never>>,
    '/guide/update-theme': RouteRecordInfo<'/guide/update-theme', '/guide/update-theme', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/releases': RouteRecordInfo<'/releases', '/releases', Record<never, never>, Record<never, never>>,
  }
}
