/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/components/': RouteRecordInfo<
      '/components/',
      '/components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/SakuraGlitchText': RouteRecordInfo<
      '/components/SakuraGlitchText',
      '/components/SakuraGlitchText',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/SakuraTypewriter': RouteRecordInfo<
      '/components/SakuraTypewriter',
      '/components/SakuraTypewriter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/': RouteRecordInfo<
      '/examples/',
      '/examples',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/animation': RouteRecordInfo<
      '/examples/animation',
      '/examples/animation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/config': RouteRecordInfo<
      '/examples/config',
      '/examples/config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/': RouteRecordInfo<
      '/guide/',
      '/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/getting-started/frontmatter-config': RouteRecordInfo<
      '/guide/getting-started/frontmatter-config',
      '/guide/getting-started/frontmatter-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/getting-started/installation': RouteRecordInfo<
      '/guide/getting-started/installation',
      '/guide/getting-started/installation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/getting-started/site-config': RouteRecordInfo<
      '/guide/getting-started/site-config',
      '/guide/getting-started/site-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/getting-started/theme-config': RouteRecordInfo<
      '/guide/getting-started/theme-config',
      '/guide/getting-started/theme-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/getting-started/update': RouteRecordInfo<
      '/guide/getting-started/update',
      '/guide/getting-started/update',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/special-pages': RouteRecordInfo<
      '/guide/special-pages',
      '/guide/special-pages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theme-config/404-page': RouteRecordInfo<
      '/guide/theme-config/404-page',
      '/guide/theme-config/404-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theme-config/footer': RouteRecordInfo<
      '/guide/theme-config/footer',
      '/guide/theme-config/footer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theme-config/home-page': RouteRecordInfo<
      '/guide/theme-config/home-page',
      '/guide/theme-config/home-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theme-config/links-page': RouteRecordInfo<
      '/guide/theme-config/links-page',
      '/guide/theme-config/links-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theme-config/nav': RouteRecordInfo<
      '/guide/theme-config/nav',
      '/guide/theme-config/nav',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theme-config/other': RouteRecordInfo<
      '/guide/theme-config/other',
      '/guide/theme-config/other',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theme-config/pagination': RouteRecordInfo<
      '/guide/theme-config/pagination',
      '/guide/theme-config/pagination',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theme-config/post-list': RouteRecordInfo<
      '/guide/theme-config/post-list',
      '/guide/theme-config/post-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theme-config/post-page': RouteRecordInfo<
      '/guide/theme-config/post-page',
      '/guide/theme-config/post-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theme-config/sidebar': RouteRecordInfo<
      '/guide/theme-config/sidebar',
      '/guide/theme-config/sidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/releases': RouteRecordInfo<
      '/releases',
      '/releases',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    '../node_modules/.pnpm/valaxy@0.26.10_@babel+parser@7.28.5_@types+markdown-it@14.1.2_@types+node@22.9.0_@vue+c_8678bbc3b0fc3e5d930fbd2f480d6f4b/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/components/index.md': {
      routes:
        | '/components/'
      views:
        | never
    }
    'pages/components/SakuraGlitchText.md': {
      routes:
        | '/components/SakuraGlitchText'
      views:
        | never
    }
    'pages/components/SakuraTypewriter.md': {
      routes:
        | '/components/SakuraTypewriter'
      views:
        | never
    }
    'pages/examples/index.md': {
      routes:
        | '/examples/'
      views:
        | never
    }
    'pages/examples/animation.md': {
      routes:
        | '/examples/animation'
      views:
        | never
    }
    'pages/examples/config.md': {
      routes:
        | '/examples/config'
      views:
        | never
    }
    'pages/guide/index.md': {
      routes:
        | '/guide/'
      views:
        | never
    }
    'pages/guide/getting-started/frontmatter-config.md': {
      routes:
        | '/guide/getting-started/frontmatter-config'
      views:
        | never
    }
    'pages/guide/getting-started/installation.md': {
      routes:
        | '/guide/getting-started/installation'
      views:
        | never
    }
    'pages/guide/getting-started/site-config.md': {
      routes:
        | '/guide/getting-started/site-config'
      views:
        | never
    }
    'pages/guide/getting-started/theme-config.md': {
      routes:
        | '/guide/getting-started/theme-config'
      views:
        | never
    }
    'pages/guide/getting-started/update.md': {
      routes:
        | '/guide/getting-started/update'
      views:
        | never
    }
    'pages/guide/special-pages.md': {
      routes:
        | '/guide/special-pages'
      views:
        | never
    }
    'pages/guide/theme-config/404-page.md': {
      routes:
        | '/guide/theme-config/404-page'
      views:
        | never
    }
    'pages/guide/theme-config/footer.md': {
      routes:
        | '/guide/theme-config/footer'
      views:
        | never
    }
    'pages/guide/theme-config/home-page.md': {
      routes:
        | '/guide/theme-config/home-page'
      views:
        | never
    }
    'pages/guide/theme-config/links-page.md': {
      routes:
        | '/guide/theme-config/links-page'
      views:
        | never
    }
    'pages/guide/theme-config/nav.md': {
      routes:
        | '/guide/theme-config/nav'
      views:
        | never
    }
    'pages/guide/theme-config/other.md': {
      routes:
        | '/guide/theme-config/other'
      views:
        | never
    }
    'pages/guide/theme-config/pagination.md': {
      routes:
        | '/guide/theme-config/pagination'
      views:
        | never
    }
    'pages/guide/theme-config/post-list.md': {
      routes:
        | '/guide/theme-config/post-list'
      views:
        | never
    }
    'pages/guide/theme-config/post-page.md': {
      routes:
        | '/guide/theme-config/post-page'
      views:
        | never
    }
    'pages/guide/theme-config/sidebar.md': {
      routes:
        | '/guide/theme-config/sidebar'
      views:
        | never
    }
    'pages/releases.md': {
      routes:
        | '/releases'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
